# Generated by Django 3.2.12 on 2022-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('star', models.FloatField(null=True)),
                ('movie_rating', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('director', models.CharField(max_length=100, null=True)),
                ('actors', models.CharField(max_length=400, null=True)),
                ('summary', models.TextField(null=True)),
                ('review', models.TextField(null=True)),
                ('nmf_topic', models.IntegerField(null=True)),
                ('lda_topic', models.IntegerField(null=True)),
                ('image_link', models.TextField(null=True)),
            ],
        ),
    ]
