# Generated by Django 3.2.12 on 2022-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierec',
            name='wnfrjfl',
            field=models.TextField(null=True),
        ),
    ]
